name: dist
on:
  push:
    tags:
    - '*'
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install --silent
      - run: npm run build
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

