name: dist
on:
  push:
    tags:
    - '*'
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install --silent
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          keep_history: true
          allow_empty_commit: true
          build_dir: dist
          committer_name: bot
          committer_email: <>
          commit_message: ${{ env.GITHUB_SHA }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

